// Generated by gencpp from file stage_ros/pose.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_POSE_H
#define STAGE_ROS_MESSAGE_POSE_H

#include <ros/service_traits.h>


#include <stage_ros/poseRequest.h>
#include <stage_ros/poseResponse.h>


namespace stage_ros
{

struct pose
{

typedef poseRequest Request;
typedef poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose
} // namespace stage_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stage_ros::pose > {
  static const char* value()
  {
    return "175f0fd52bd8fce3593f95b1f031b849";
  }

  static const char* value(const ::stage_ros::pose&) { return value(); }
};

template<>
struct DataType< ::stage_ros::pose > {
  static const char* value()
  {
    return "stage_ros/pose";
  }

  static const char* value(const ::stage_ros::pose&) { return value(); }
};


// service_traits::MD5Sum< ::stage_ros::poseRequest> should match
// service_traits::MD5Sum< ::stage_ros::pose >
template<>
struct MD5Sum< ::stage_ros::poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stage_ros::pose >::value();
  }
  static const char* value(const ::stage_ros::poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage_ros::poseRequest> should match
// service_traits::DataType< ::stage_ros::pose >
template<>
struct DataType< ::stage_ros::poseRequest>
{
  static const char* value()
  {
    return DataType< ::stage_ros::pose >::value();
  }
  static const char* value(const ::stage_ros::poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stage_ros::poseResponse> should match
// service_traits::MD5Sum< ::stage_ros::pose >
template<>
struct MD5Sum< ::stage_ros::poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stage_ros::pose >::value();
  }
  static const char* value(const ::stage_ros::poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage_ros::poseResponse> should match
// service_traits::DataType< ::stage_ros::pose >
template<>
struct DataType< ::stage_ros::poseResponse>
{
  static const char* value()
  {
    return DataType< ::stage_ros::pose >::value();
  }
  static const char* value(const ::stage_ros::poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGE_ROS_MESSAGE_POSE_H
