#Network:
#  epochs: 100
#  batch_size: 6
#  n_steps: 16
#  dataset: "DVS128Gesture"
#  data_path: "../datasets/DvsGesture"
#  rule: "TSSLBP"
#  lr: 0.0005
#  loss: "kernel"
#  n_class: 11
#  desired_count: 5
#  undesired_count: 1
#  tau_m: 5
#  tau_s: 2
#  model: "LIF"
#
#Layers:
#
#    conv_1:  #32*32   #128*128
#      type: "conv"
#      in_channels: 2
#      out_channels: 128
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 0.7
#      norm: True
#
#    pooling_1:
#      type: "pooling"
#      kernel_size: 2
#      threshold: 0.6
#
#    conv_2:  #16*16  64
#      type: "conv"
#      in_channels: 128
#      out_channels: 128
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 0.7
#      norm: True
#
#    pooling_2:
#      type: "pooling"
#      kernel_size: 2
#      threshold: 0.6
#
#    dropout_0:
#      type: "dropout"
#      p: 0.5
#
#    conv_3: #8*8  32
#      type: "conv"
#      in_channels: 128
#      out_channels: 128
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 0.7
#      norm: True
#
#    pooling_3:
#      type: "pooling"
#      kernel_size: 2
#      threshold: 0.4   #4*4  16
#
#    conv_4: #8*8  16
#      type: "conv"
#      in_channels: 128
#      out_channels: 128
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 0.8
#      norm: True
#
#    pooling_4:
#      type: "pooling"
#      kernel_size: 2
#      threshold: 0.4   #4*4
#
#    conv_5: #8*8  8
#      type: "conv"
#      in_channels: 128
#      out_channels: 128
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 0.8
#      norm: True
#
#    pooling_5:
#      type: "pooling"
#      kernel_size: 2
#      threshold: 0.4   #4*4
#
#    dropout_1:
#      type: "dropout"
#      p: 0.5
#
#
#    FC_1:
#      type: "linear"
#      n_inputs: 2048    #1024
#      n_outputs: 512
#      weight_scale: 1
#      threshold: 0.8
#
#    dropout_2:
#      type: "dropout"
#      p: 0.5
#
#    FC_2:
#      type: "linear"
#      n_inputs: 512      #1024
#      n_outputs: 110
#      weight_scale: 1
#      threshold: 0.8
#
##    dropout_3:
##      type: "dropout"
##      p: 0.3
#
#
#    output:
#      type: "linear"
#      n_inputs: 110
#      n_outputs: 11
#      weight_scale: 1
#      threshold: 0.8


#Network:
#  epochs: 100
#  batch_size: 8
#  n_steps: 500
#  dataset: "DVS128Gesture"
#  data_path: "../datasets/DvsGesture"
#  rule: "TSSLBP"
#  lr: 0.0005
#  loss: "kernel"
#  n_class: 11
#  desired_count: 5
#  undesired_count: 1
#  tau_m: 5
#  tau_s: 2
#  model: "LIF"
#
#Layers:
#
#    conv_1:  #32*32   #128*128
#      type: "conv"
#      in_channels: 2
#      out_channels: 64
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 1
#      norm: False
#
#    pooling_1:
#      type: "pooling"
#      kernel_size: 2
#      threshold: 1
#
#    conv_2:  #16*16  64
#      type: "conv"
#      in_channels: 64
#      out_channels: 128
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 1
#      norm: False
#
#    pooling_2:
#      type: "pooling"
#      kernel_size: 2
#      threshold: 1
#
#    dropout_0:
#      type: "dropout"
#      p: 0.5
#
#    conv_3: #8*8  32
#      type: "conv"
#      in_channels: 128
#      out_channels: 256
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 0.7
#      norm: True
#
#
#
#    conv_4: #8*8  16
#      type: "conv"
#      in_channels: 256
#      out_channels: 256
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 1
#      norm: False
#
#    pooling_4:
#      type: "pooling"
#      kernel_size: 2
#      threshold: 1   #4*4
#
#    conv_5: #8*8  8
#      type: "conv"
#      in_channels: 256
#      out_channels: 512
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 1
#      norm: True
#
#
#    dropout_1:
#      type: "dropout"
#      p: 0.5
#
#    conv_6: #8*8  8
#      type: "conv"
#      in_channels: 512
#      out_channels: 512
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 1
#      norm: False
#
#    pooling_6:
#        type: "pooling"
#        kernel_size: 2
#        threshold: 1   #4*4
#
#    dropout_6:
#        type: "dropout"
#        p: 0.5
#
#    conv_7: #8*8  8
#      type: "conv"
#      in_channels: 512
#      out_channels: 512
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 1
#      norm: False
#
#
#
#    dropout_7:
#        type: "dropout"
#        p: 0.5
#
#    conv_8: #8*8  8
#      type: "conv"
#      in_channels: 512
#      out_channels: 512
#      kernel_size: 3
#      weight_scale: 1
#      padding: 1
#      threshold: 1
#      norm: False
#
#    pooling_8:
#        type: "pooling"
#        kernel_size: 2
#        threshold: 1   #4*4
#
#    dropout_8:
#        type: "dropout"
#        p: 0.5
#
#
#    FC_1:
#      type: "linear"
#      n_inputs: 512    #1024
#      n_outputs: 4096
#      weight_scale: 1
#      threshold: 1
#
#    dropout_2:
#      type: "dropout"
#      p: 0.5
#
#    FC_2:
#      type: "linear"
#      n_inputs: 4096      #1024
#      n_outputs: 4096
#      weight_scale: 1
#      threshold: 1
#
##    dropout_3:
##      type: "dropout"
##      p: 0.3
#
#
#    output:
#      type: "linear"
#      n_inputs: 4096
#      n_outputs: 11
#      weight_scale: 1
#      threshold: 1
#


Network:
  epochs: 100
  batch_size: 16
  n_steps: 500
  dataset: "DVS128Gesture"
  data_path: "../datasets/DvsGesture"
  rule: "mTSSLBP"
  lr: 0.0005
  loss: "kernel"
  n_class: 11
  tau_m: 5
  tau_s: 3
  model: "LIF"

Layers:

    conv_1:  #32*32   #128*128
      type: "conv"
      in_channels: 2
      out_channels: 16
      kernel_size: 3
      weight_scale: 1
      padding: 1
      threshold: 1
      norm: False

    pooling_1:
      type: "pooling"
      kernel_size: 2
      threshold: 1

    conv_2:  #16*16  64
      type: "conv"
      in_channels: 16
      out_channels: 32
      kernel_size: 3
      weight_scale: 1
      padding: 1
      threshold: 1
      norm: False

    pooling_2:
      type: "pooling"
      kernel_size: 2
      threshold: 1

#    dropout_0:
#      type: "dropout"
#      p: 1

    conv_3: #8*8  32
      type: "conv"
      in_channels: 32
      out_channels: 64
      kernel_size: 3
      weight_scale: 1
      padding: 1
      threshold: 1
      norm: False

    pooling_3:
      type: "pooling"
      kernel_size: 2
      threshold: 1   #4*4  16



    FC_1:
      type: "linear"
      n_inputs: 1024   #1024
      n_outputs: 300
      weight_scale: 1
      threshold: 1



    FC_2:
      type: "linear"
      n_inputs: 300      #1024
      n_outputs: 11
      weight_scale: 1
      threshold: 1

